### ISSUE TITLE
Additional boundary drivers

### ISSUE THREAD

**Issue by iomsn** [pencil-code/pencil-code#1]
Currently we have a few different drivers for the boundaries which prescribe a velocity field, e.g. bc_force_axy_sin_cos in boundcond.f90. I see the need for implementing more complex drivers like footpoint motins. Those would require individual parameters like the strength of the driving. However, all the parameters for boundcond.f90 are given in the &run_pars group name. A neat solution would be to move such boundary drivers into one directory and access them like the initial conditions. That way we could have one new group entry, e.g. &boundary_drivers.

**Comment by wdobler** [comment]
You are aware of the work of Sven Bingert and Philippe Bourdin? If I recall the details correctly, they use the Pencil code with a horizontal velocity field at the lower boundary that is extracted from observations of the solar photosphere.
  So we already have some sort of footpoint motion.
And, yes, if we get more boundary drivers, it would be good to group them together.

**Comment by iomsn** [comment]
That sounds like what I need. In which modules was that implemented?

**Comment by jwarne** [comment]
Hi Simon,

you can find the driver from Sven in special/coronae.f90

Cheers,
Jörn

**Comment by iomsn** [comment]
Thanks, Jörn. There is also a velocity driver in special/solar_corona.f90. Both seem to be rather similar at a first glance.
