### ISSUE TITLE
python/pencil and python/pencilnew

### ISSUE THREAD

**Issue by jaarnes** [pencil-code/pencil-code#12]
Is it about time to delete the old python directory python/pencil?

Having two sets of python files is confusing for new users and annoying for people who want to update the routines. Would we loose any functionality by deleting python/pencil and moving all files from python/pencilnew to python/.  ?

**Comment by dhrubaditya** [comment]
Do we have all the functionalities in the new ones ? Is everybody sure
about that ? Boris, what would you say ?
with my best regards
dhrubaditya

---

Dhrubaditya MITRA
NORDITA
Roslagstullsbacken 23
106 91 Stockholm

## Sweden

**Comment by jaarnes** [comment]
After a few tests I can answer that Druba. It looks like python/pencilnew is far from ready to replace python/pencil, as there are dependencies all over the place. I'll try to do some work on the python routines in the near future let you know when they are ready to be used.

**Comment by iomsn** [comment]
Pencilnew was created after discussions during the last PC meeting to rewrite the python routines in a more consistent way with a clean standard coding style (https://github.com/pencil-code/pencil-code/wiki/PythonCodingStyle) and fully object oriented. It is slowly gaining more and more routines, but does not contain all the original ones yet. If the naming is confusing we can rename it to something else.

**Comment by jaarnes** [comment]
In my opinion the naming is fine, but I think it should be a priority to finish the transition from pencil to pencilnew to avoid having two branches of the pyhthon routines.

One question regarding this:
I updated the **init**.py file in the visu module, but see that the routines in this folder don't work as they have problems with libraries not being loaded properly. Is it necessary to load the libraries (numpy, os, pencilnew.read, etc.) in each animation routine in visu, or could this also be done in the **init**.py to avoid repeated lines of code?

**Comment by fredgent** [comment]
I recently added none cartesian coordinates to python math routines, and 
extended them to be able to handle any shape array as opposed to only 
farray. I am not aware of this applying to pencilnew.

Fred

**Comment by iomsn** [comment]
Jorgen: if you need any libraries for your routines it is best to load them inside the routines, otherwise they will be visible to the users in their python session, which is not desirable. Have a look at ts.py in pencilnew.
Fred: Did you add it to pencil or pencilnew?

**Comment by iomsn** [comment]
Fred: pencil and pencilnew are independent. The idea is to replace pencil by pencilnew as soon as we have updated (rewritten) the routines. There is nothing to worry about for anyone who uses or modifies the pencil routines, they will work just as always. If you modify 'pencil' that's no problem.

**Comment by WenyinWei** [comment]
It is a little strange that in Python 3.6, the module pencilnew/export/create_h5. has syntax errors. 

For the function create_aver_sph, the input parameters syntax should be modified.
`   def create_aver_sph(
    filename,
    dataset,
    fields,
    (nz, ny, nx, nt),
    (z, y, x, t),.....`

The round brackets of (nz, ny,...) are not allowed in my Python 3.6 syntax. This error could be avoided by deleting the brackets but not a good solution.(replacing by square brackets doesn't work) Anybody volunteer to fix the bug?

**Comment by fredgent** [comment]
Hi Wenyin,

I have pushed a change to the module to fit the python 3 syntax. Not 
very happy that tuples and arrays appear not to work, but perhaps it can 
be made more elegant in future.

Regards,

Fred

**Comment by SimonCan** [comment]
Dear Python Users,

after updating routines from pencil to pencilnew and tests performed on pencilnew I believe that we are ready for merging pencilnew into pencil. We would then move the current python/pencil directory into python/pencilold. That way we can keep using our old scripts by only replacing
import pencil as pc
by
import pencilold as pc

If there is no strong objection we will proceed with this.

Cheers

Simon

**Comment by dhrubaditya** [comment]
I have no objection.
with my best regards
dhrubaditya



-----------------------------------------------------------
Dhrubaditya MITRA
NORDITA
Roslagstullsbacken 23
106 91 Stockholm
Sweden
-----------------------------------------------------------

with my best regards
dhrubaditya



-----------------------------------------------------------
Dhrubaditya MITRA
NORDITA
Roslagstullsbacken 23
106 91 Stockholm
Sweden
-----------------------------------------------------------
