### ISSUE TITLE
comment on commit ea51334 by Matthias

### ISSUE THREAD

**Issue by mppiyali** [pencil-code/pencil-code#13]
Hi Matthias 

I noticed this problem a bit late and hence cannot directly reply to the commit mesg from Github which I deleted.

Do you think adding the ldownsampled flag and corresponding changes in pc_varcontent may have created an error? What does this flag do? I am asking this because I have data from a 2d run with lnrho, lntt, magnetic field, ionisation and aux variables like shock, radiative fluxes which I was able to read and plot correctly using IDL till a fortnight ago but now after this change executing a pc_read_var gives a syntax error at line number 314 in pc_read_var where it calls pc_varcontent and on output does not create a structure array for the magnetic vector potential. Also upon printing the output x,y,z coordinate vectors from pc_read_var command contain NaNs. Do you know what the problem might be? I tried reading several VAR files in this run unsuccessfully.

Cheers
Piyali

**Comment by mrheinhardt** [comment]
?Hi Piyali,

I'll look into this later today. Could you please check in the run?

Best,

Matthias

**Comment by PABourdin** [comment]
```
Hello Matthias,
```

> I'll look into this later today. Could you please check in the run?

Might be that a default value setting for "ldownsampled" is missing for
reading data from old runs? Should be easy to fix.

Best greetings,

```
Philippe.
```

**Comment by PABourdin** [comment]
```
Hello Piyali
```

could you please try the latest version and report back with the
complete error message you get?

Thanks and best greetings,

```
Philippe.
```

**Comment by mrheinhardt** [comment]
Hi Philippe,

   Might be that a default value setting for "ldownsampled" is missing for
   reading data from old runs? Should be easy to fix.

No, ldownsampled is set true if the name of the read-in varfile has the form VARd<number>, otherwise
false.

Best,
Matthias
