### ISSUE TITLE
Preferred Citation(s)

### ISSUE THREAD

**Issue by augustfly** [pencil-code/pencil-code#17]
I am a data/software editor with the AAS Journals (ApJ/AJ). Pencil Code has been mentioned in a submitted manuscript, but the authors have not added a proper attribution. Could you please let me know if there are 1 or more preferred citations for this code (from among the [reference list here](http://pencil-code.nordita.org/references.php) I presume). 

Adding this material to the ReadMe landing page for this repository may also help users ensure proper attribution of this code.  You can read more about how the AAS Journals are trying to improve software citation in our [Journal's software policy](http://journals.aas.org/policy/software.html).

**Comment by mrheinhardt** [comment]
Hi,



   I am a data/software editor with the AAS Journals (ApJ/AJ). Pencil Code has been mentioned in a

   submitted manuscript, but the authors have not added a proper attribution. Could you please let me

   know if there are 1 or more preferred citations for this code (from among the reference list here<http://pencil-code.nordita.org/references.php> I

   presume).


Dobler & Brandenburg (2002) is surely a well suited reference (w.r.t. the mathematical foundations

also Brandenburg (2003?).


  Adding this material to the ReadMe landing page for this repository may also help users ensure proper

  attribution of this code.


Yes, true. Thanks for his recommendation.


Best regards,

M. Rheinhardt

**Comment by augustfly** [comment]
Thank you @mrheinhardt very much!! I will pass this information back to the authors.

**Comment by AxelBrandenburg** [comment]
Dear August,
There is also an entry in ASCL; see

  http://adsabs.harvard.edu/abs/2010ascl.soft10060B

Thanks, Axel

**Comment by augustfly** [comment]
Thanks, @AxelBrandenburg. I had overlooked that. We are happy to use which ever citation you think best for this code.
