### ISSUE TITLE
compilation fails after update: complains about gpu

### ISSUE THREAD

**Issue by nishkpph** [pencil-code/pencil-code#18]
The code fails to compile after an update complaining about GPU related issue.
I am not using GPU and tried both mpi (mpif90) and nompi (gfortran) with explicit
mention of "nogpu" and also without, and get the following error:

gpu_astaroth_ansi.o: In function `rhs_gpu_c_':
gpu_astaroth_ansi.c:(.text+0xf3): undefined reference to `RKintegration'
gpu_astaroth_ansi.o: In function `initialize_gpu_c_':
gpu_astaroth_ansi.c:(.text+0xbc): undefined reference to `intitializeGPU'
gpu_astaroth_ansi.o: In function `finalize_gpu_c_':
gpu_astaroth_ansi.c:(.text+0xc3): undefined reference to `finalizeGPU'
collect2: error: ld returned 1 exit status
Makefile:2352: recipe for target 'start.x' failed
make[2]: *** [start.x] Error 1

Does one know what causes this?

Regards,
nishant

**Comment by dhrubaditya** [comment]
Is this the latest version that you are using. I think this problem
existed, but Matthias fixed this in a recent update. Or maybe I am
wrong.
with my best regards
dhrubaditya



-----------------------------------------------------------
Dhrubaditya MITRA
NORDITA
Roslagstullsbacken 23
106 91 Stockholm
Sweden
-----------------------------------------------------------

**Comment by nishkpph** [comment]
Thanks Dhruba. I updated again and at revision 74467.
The code worked fine this morning, and fails only after I updated src today.

Regards,
nishant

**Comment by AxelBrandenburg** [comment]
I think this was a change that Matthias did just last night before
leaving for vacation. It maybe compiler-dependent. so try to circument
this somehow.
Axel

**Comment by nishkpph** [comment]
Thanks Axel. Tried Cray compiler on Sisu and everything seems to work there.
Regards,
nishant

**Comment by nishkpph** [comment]
Thanks Axel. Tried Cray compiler on Sisu and everything seems to work there.
Regards,
nishant

**Comment by nishkpph** [comment]
Hi,

After making fresh links to $PENCIL_HOME/src as suggested by Matthias, everything
now works also on my laptop. The issue being resolved, I will close this topic here.

Many thanks for your responses,
with regards,
nishant
