### ISSUE TITLE
Update on Python Package

### ISSUE THREAD

**Issue by andreas-schreiber** [pencil-code/pencil-code#2]
Hi PC Team,
we discussed to update our python package and do an overhaul in style and structure. I encourage all python users and contributors to participate! As soon as we have a decision on how to structure the code we will have an transition phase where we will have two python modules in our repository. Feel free to add your features to the new one. When everything is converted/added to the new package the old one will be deleted/replaced. There probably will be no backwards compatibility! 

Please check my email on a first draft on python pc package structure. The more contribute, the faster we're done!
best wishes

**Comment by iomsn** [comment]
Hi Andreas,

werde am Wochenende auch was dazu beitragen. Bin im Moment noch in 
Newcastle.

Gruesse

Simon

**Comment by iomsn** [comment]
Hi,

there are several steps for improving the structure of the Python routines and the routines themselves:
1. Restructure the directories according to the tasks the routines perform.
2. Confirm to a uniform programming style, as we do with the Fortran routines.
3. Objectify the routines.
4. Parallelize some of the routines to speed up reading and computing.
I wouldn't be worried too much about possible loss of backward compability. Most of the routines should not be effected by that anyways and it shouldn't take much time to adapt one's routines.

Cheers

Simon

**Comment by iomsn** [comment]
For the directory structure I would suggest to split the routines into main areas:
IO: all the reading and possible writing routines
math: all the mathematical operators like derivatives and products
plot: all the visualization
export: export functions to different data formats
tool_kit: high level convenience functions which are often used
This can be changed anytime without any interference with the Python users. After all it does not matter where the files reside as long as we have the **init**.py files set up correctly.

Cheers

Simon

**Comment by wdobler** [comment]
Simon Candelaresi writes:

> there are several steps for improving the structure of the Python routines and
> the routines themselves:
> 1. Restructure the directories according to the tasks the routines perform.
> 2. Confirm to a uniform programming style, as we do with the Fortran routines.
> 3. Objectify the routines.
> 4. Parallelize some of the routines to speed up reading and computing.

One thing that always irritated me when using the Python interface is that
some of the routines that read data also try to plot them.
  It may be convenient for command-line use to have an extra option that
triggers this, but I think the default should be to never do anyting other
than reading. So

  ts = pc.read_ts()

should not do any visualization, but

  pc.read_ts(visualize=True)

or

  pc.read_ts(show=True)

or some such may.

W o l f g a n g

**Comment by iomsn** [comment]
Wolfgang, I completely agree. Reading routines should not plot any data, at least not by default. We briefly discussed that during the meeting. That is one thing we want to change.

Simon

**Comment by andreas-schreiber** [comment]
So, change would be

plot -> visualization
and
tool_kit -> toolkit

I would agree with
plot -> visu
and
tool_kit -> toolkit

because plot is for me a bit of an outdated phrase. We do and will do more than just plotting! And getting rid of '_' and use an abbreviation for visualization makes workflow faster and easier.

I still wonder whether its a good idea not to put vtk stuff aside, or all classic read methods in a separate folder. I know they are io, but in my mind io is much more basic level then our read routines.

But I agree, merging diag into toolkit makes things easier. For me, diag would contain stuff like a saturation analyzer I wrote, but this could also be understood as a tool from the toolkit. I just now was thinking about having further folders in toolkit. Because I definitely would like to not have 100 unsorted methods and functions in one folder. Better thinking about a structure now.

**Comment by dhrubaditya** [comment]
Could I please add a wish-list to the list of python packages:
(as I am not promising to contribute anything, please feel free to ignore)

(i) A python code that reads the var files (and pvar files) and writes them out
in hdf5 format.
(ii) And an inverse code for that, which reads the hdf5 file (or
files) and then writes them out to var files (and pvar files)
corresponding to a pencil-code run.

with my best regards
dhrubaditya

---

Dhrubaditya MITRA
NORDITA
Roslagstullsbacken 23
106 91 Stockholm

## Sweden

**Comment by andreas-schreiber** [comment]
We should put somewhere a to-do-list. Maybe in the Wiki or directly in the repository.

**Comment by tobson** [comment]
> Maybe in the Wiki or directly in the repository.

Just a side note because not everybody may know this: The GitHub Wiki is in
fact a repository in its own right. It can be cloned/checked out with

$ git clone https://github.com/pencil-code/pencil-code.wiki.git

and

$ svn co https://github.com/pencil-code/pencil-code.wiki

  Toby

**Comment by tobson** [comment]
> Just a side note because not everybody may know this: The GitHub Wiki is
> in fact a repository in its own right.

See https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

**Comment by iomsn** [comment]
Dhruba:
(i) There should be something along the lines of a hdf5 converter in hdf5.py written by Rafael Plasmon some years ago.
(ii) Regarding the reverse it is a bit more tricky, since not all hdf5 or vtk data is compatible with the Pencil Code. Some time ago I wrote a converter from my Lagrangian code to PC which does it during the start process: initial_condition/import_glemur.f90. For different kind of VTK data that of course needs to be adapted.

Andreas:
We have a rough todo list already. Would you like to propose a more detailed one?
Personally I would prefer 'vis' to 'visu', but I won't squabble about it.
