### ISSUE TITLE
File "data/xyaverages.dat" corrupted!

### ISSUE THREAD

**Issue by nishkpph** [pencil-code/pencil-code#20]
Sometimes very high values (larger than 1000 at some time,
when typical numbers should be around +/-0.1) for particularly
the variable "uxmz" are generated in the "xyaverages.dat".
When trying to read using "pc_read_xyaver", I get the Warning
message: File "data/xyaverages.dat" corrupted!

Has somebody seen this before? Are there some known issues
related to this?

Regards,
nishant

**Comment by iomsn** [comment]
Hi Nishant,
are you using the python routines for reading? I haven't seen this before. If you could send me your simulation files I could try to reproduce the issue.
Simon

**Comment by AxelBrandenburg** [comment]
these are formatted data files, so if they are corrupt,
you can check and fix this.
Axel

**Comment by nishkpph** [comment]
Hi Simon,

Very sorry for being late.
I tried reading it using idl and the problem appears to occur when averages
are computed for more than about 1000 times, interestingly only for uxmz!
The xyaver file is about 507 MB and the run is checked-in:
pencil-code/nishant/forced/shear/sd_vd/cc7_128_r0

Do I need to send zipped source files for this run?

Best regards,
nishant


On Sat, Jul 29, 2017 at 3:43 PM, Simon Candelaresi <notifications@github.com

**Comment by PABourdin** [comment]
It might well be that if a column is to narrow, your compiler marks these entries with a place holder like "######". You can either rerun or try to fix such problems manually in your files.
