### ISSUE TITLE
lsode_for_chemistry

### ISSUE THREAD

**Issue by wangh16** [pencil-code/pencil-code#21]
I use pencil-code to simulate the 3D H2/02 turbulence flame, and after  31800 steps , the program incorrect report:
DLSODE- Warning. internal T(=R1) and H(=R2) are such that in the machine,T+H=T on the next step(H = step size). Solver will continue anyway
              R1=0.435645e-5,R2=0.254653e-30
DLSODE- Above warning has been issued I1 times.It will not be issued again for this problem 
             I1=10
And I also tried to change timestep_LSODE to timestep,but pencil_check reported some error. 
How can I slove it? Thanks

**Comment by PABourdin** [comment]
Using double precision might help, here. Thanks.
