### ISSUE TITLE
Request for git permission to translate documents

### ISSUE THREAD

**Issue by WenyinWei** [pencil-code/pencil-code#26]
Hello guys, I am an undergraduate student from Tsinghua University, China. Would you be willing to let me translate the document to Chinese? That would be helpful to spread pencil-code all over the world. And I  promise I would not to destroy anything when committing changes to pencil-code.

**Comment by wlyra** [comment]
That sounds awesome. Please do :-)


On Oct 5, 2018, at 7:19 PM, Wenyin Wei <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello guys, I am an undergraduate student from Tsinghua University, China. Would you be willing to let me translate the document to Chinese? That would be helpful to spread pencil-code all over the world. And I promise I would not to destroy anything when committing changes to pencil-code.

**Comment by WenyinWei** [comment]
![image](https://user-images.githubusercontent.com/33152225/46566553-6b08af80-c953-11e8-9eed-f8a27775e9ba.png)
It seems that I need to get the permission? Would you mind adding me to your contributor list?

**Comment by tobson** [comment]
Hi there,

I suspect you'll be given permission very soon if it hasn't happened
already, but I'd like to point out that what you could also do is fork the
code temporarily, make your changes, and then submit them to the main
Pencil Code repository as a pull request.

See https://help.github.com/articles/creating-a-pull-request-from-a-fork/
and https://guides.github.com/activities/forking/ for details.

Best,
  Toby

**Comment by WenyinWei** [comment]
That's a good suggestion of Toby to fork the repository. In fact, I have made some changes to the pencil-code which I have git pulled. But only a few files need to be edited. So I am not anxious for the permission. Thanks for your reply! Enjoy working with all of you.

Best,
Wenyin
