### ISSUE TITLE
How to change NCHEMSPEC for a run?

### ISSUE THREAD

**Issue by himakarganti** [pencil-code/pencil-code#31]
I have not had success so far in increasing the number of species for a run, I tried the following and all of them fail:

1. Changed _cparam.local_ as follows to include additional species:
integer, parameter :: nchemspec=13
 - pc_build fails
 - pc_run fails

2. Changed _Makefile.local_ as follows to include additional species:
NCHEMSPEC = 13
 - pc_build successfully compiles
 - pc_run fails with the following error:

_Running 'env MODULE_PREFIX=__ MODULE_INFIX=_MOD_ MODULE_SUFFIX= /usr/bin/time -p ./src/start.x'...
SVN: -------            v.         (                   ) $Id$
WARNING:  read_namelist: namelist "init_pars" has an error (5010)!
STOPPED: read_all_init_pars: Please fix all above WARNINGs for file "start.in"_

I have added all species, boundary conditions & values in start.in but still get the above Warning, which stops the run.

Can anyone please help with this issue?

**Comment by jnskrueger** [comment]
Hi,

this is a rather cryptic error. Could you send me the case? (Just
Makefile.local, cparam.local, start.in and run.in)
I would guess you have not allocated enough species in cparam.local. It
should say something like nchemspec contribution 13 or similar.

Kind regards,
Jonas

Am Mo., 28. Jan. 2019 um 20:04 Uhr schrieb Himakar Ganti <
notifications@github.com>:

**Comment by himakarganti** [comment]
Thanks for the help Jonas. Here is the full case, including the chemistry:
[init_cond_1D.zip](https://github.com/pencil-code/pencil-code/files/2804928/init_cond_1D.zip)

I did change the commented out line 

! NCHEMSPEC CONTRIBUTION=8*1 to 13*1, 

before the steps in the first comment. This failed too.

**Comment by jnskrueger** [comment]
Hi Himakar,

I will have a closer look tomorrow (trying to run the code etc. ). What I
can tell right now is that

! NCHEMSPEC CONTRIBUTION 13

is the way to go, remove all other nchemspec stuff like integer parameter
and the like.
The NCHEMSPEC CONTRIBUTION is used to preprocess the source files. It is
not even a parameter, it is hard-wired-compiled in the code.
Might be that you have to give another array in start.in or something like
it. I'll look into it.

Kind regards,
Jonas

Am Mo., 28. Jan. 2019 um 22:02 Uhr schrieb Himakar Ganti <
notifications@github.com>:

**Comment by himakarganti** [comment]
Jonas,

I ran it like you said and I get the same error as before:

Running 'env MODULE_PREFIX=__ MODULE_INFIX=_MOD_ MODULE_SUFFIX= /usr/bin/time -p ./src/start.x'...
SVN: -------            v.         (                   ) $Id$
WARNING:  read_namelist: namelist "init_pars" has an error (5010)!

STOPPED: read_all_init_pars: Please fix all above WARNINGs for file "start.in"
=== BEGIN SAMPLE "start.in" ===>
&init_pars
STOP 1
/
&eos_init_pars
/
&hydro_init_pars
/
&density_init_pars
/
&entropy_init_pars
/
&chemistry_init_pars
/
&NSCBC_init_pars
/
<=== END SAMPLE ===

**Comment by himakarganti** [comment]
Thanks Jonas,

I changed it in the cparam.local file as:

! NCHEMSPEC CONTRIBUTION 13*1 - it now compiles, but I run into another different error:

FATAL ERROR:  calc_pencils_density: NaNs in p%glnrho)

The run stops after doing the first t=0 estimate. A more detailed error output is:

Bcs for       lnTT,  x: <  set:a2>, y: <       p>,  z: <       p>
 denergy_dt: cs2 =   3788706246.4863052     
 denergy_dt: max(advec_cs2) =   0.0000000000000000E+000
 dchemistry_dt: SOLVE dchemistry_dt
 inlet_profile: uniform
 inlet_YY_profile: uniform,
 density:iproc,it,m,n=           0           1           4           4
 density:f(:,m,n,ilnrho)=                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN                       NaN
FATAL ERROR:  calc_pencils_density: NaNs in p%glnrho)

**Comment by jnskrueger** [comment]
Hi,

alright, thats the error I get as well. I can look into that after 17:00
UTC+1 today. Maybe something with the boundary conditions at the 'outlet'
or a bad initialization of the density, or nscbc - boundary conditions?
Kind regards,
Jonas

Am Di., 29. Jan. 2019 um 01:10 Uhr schrieb Himakar Ganti <
notifications@github.com>:

**Comment by jnskrueger** [comment]
You could try to adapt the case in samples/1d-tests/H2_flamespeed to your
conditions, and see where it fails.....
more information later.

Am Di., 29. Jan. 2019 um 13:56 Uhr schrieb Jonas Krueger <
jnskrueger@gmail.com>:

**Comment by jnskrueger** [comment]
Soooo, I had another go.
I am comparing to Natalias samples/1d_tests/H2_flamespeed. Somehow, there
are already NaNs in the net_reactions.dat file produced in the data folder.
There should not be.

Replacing the chem.inp from H2_flamespeed into your case results in a
working case.... which is super rare : )
Moreover, your case also crashes if I just comment out all reactions.
My first guess is that something is formatted wrong with your chem.inp
file, or there are typos in the THERMO ALL that result in a NaN density
somewhere.
Try salvaging some thermal data from Natalia, and if that works, adapt line
by line to your data.

Kind regards,
Jonas
Try looking at the formatting of the chem.inp file from Natalia.

Am Di., 29. Jan. 2019 um 01:10 Uhr schrieb Himakar Ganti <
notifications@github.com>:

**Comment by himakarganti** [comment]
Thank you Jonas,

I did use the H2_flamespeed sample case to set this configuration and now I did reformat chem.inp to the format of Natalias, but still get the same issue. pc_run does generate the chem.out file in the /data folder and it has all the species & reactions. 

The FATAL ERROR is NANs for the Logarithmic Pressure Gradient values, resulting in a zero density values for subsequent time marching. Here is another observation, after the FATAL ERROR, I do get the following:

 ---it-------t-------dt-------rhom-------TTm-------urms------uxm-------uym-------uzm-------Y1m-------Y2m-------Y3m-------Y4m-------Y5m-------Y6m-------Y7m-------Y8m----
      0  0.00E+00 1.00E-08 8.034E-03  1650.0000 2.724E+01 2.578E+01 0.000E+00 0.000E+00 1.996E-01 8.450E-03 5.708E-02 1.234E-01 1.048E-03 0.000E+00 0.000E+00 0.000E+00

for the 0th interation as output, and as we see the rhom (density value) is being estimated before time marching. The net_reactions.dat file only shows the following and appends the number of species & reactions to the file with each run:
    12    32

Here are the chemistry & NSCBC parameters:

&chemistry_init_pars
  initchem='flame_front'
!  initchem='air','flame_front'
  init_pressure=1.013e5  
  init_TT1=800.
  init_TT2=2500.
  init_ux=25.
  init_x1=-0.1
  init_x2=0.1
/

&NSCBC_init_pars
  nscbc_bc = 'subsonic_inflow:subson_nref_outflow','',''
  nscbc_bc = 'part_ref_inlet:part_ref_outlet','',''
  nscbc_sigma_in=4.0
  nscbc_sigma_out=0.28
  p_infty=1.013e5
/

**Comment by jnskrueger** [comment]
I can look into it later today. I will see if a version of your case with
less chemistry or species would be stable, since I still think that
something is not working there.

Kind regards,
Jonas

Am Di., 29. Jan. 2019 um 21:07 Uhr schrieb Himakar Ganti <
notifications@github.com>:

**Comment by himakarganti** [comment]
Thanks Jonas,

It is proven & validated mechanism, & I have been able to run it in Chemkin with matching values for ignition delays & flames speeds with the reference below:

Saxena P, Williams FA. Testing a small detailed chemical-kinetic mechanism for the combustion of hydrogen and carbon monoxide. Combust Flame 2006;145:316–23. doi:10.1016/j.combustflame.2005.10.004.

**Comment by jnskrueger** [comment]
Hi Himakar,

I did some running with the gnu debugger, and it seems to call the function
calc_pencils_log_density_pnc in density three times for startup, and then
the third time, it gives NaNs.
So something happens between the second and third call.
I have to go now, but tomorrow I will have a bit more time after work to
look into it.

You were right, the mechanism should be fine.
But since the boundary conditions also look fine, it seems to me that there
is an unwanted interaction between some modules that was not intended in
this way, which gives rubbish values.

Kind regards,
Jonas


Am Mi., 30. Jan. 2019 um 16:33 Uhr schrieb Himakar Ganti <
notifications@github.com>:

**Comment by jnskrueger** [comment]
Hi Himakar,

I chased the bug to the line

density_rhs = - p%uglnrho -p%divu

in density.f90. Something is getting NaNs there at the third call. This is
time-step independent.  Both p%uglnrho and p%divu have NaNs at the same
time. I will look into it more over the weekend.
Kind regards,
Jonas

Am Mi., 30. Jan. 2019 um 17:51 Uhr schrieb Jonas Krueger <
jnskrueger@gmail.com>:

**Comment by himakarganti** [comment]
Thanks Jonas,

Appreciate your help with this.

**Comment by jnskrueger** [comment]
Hi Himakar,

sorry, the weekend was a bit busy. I will try to look into it this evening.
Kind regards,
Jonas

Am Fr., 1. Feb. 2019 um 18:30 Uhr schrieb Himakar Ganti <
notifications@github.com>:

**Comment by jnskrueger** [comment]
Hi Himakar,

you defined OH two times in the chem.inp file. That caused a major hiccup.
in the viscosity calculations. It should be nchemspec 12 and remove one OH.
Then, another error comes up, but I will not look into that today. It at
least has no NaNs any more, but infs in the temperature. That is a quite
regular error :)

Kind regards,
Jonas

Am Mo., 4. Feb. 2019 um 10:57 Uhr schrieb Jonas Krueger <
jnskrueger@gmail.com>:

**Comment by himakarganti** [comment]
Thanks Jonas,

I corrected for that and have the same issues you are having for it. I forgot that Pencil-Code is an explicit solver, and reducing the time step to 1e-15 from 1e-8 made it run. It is running the mechanism and I am getting results for it. Thanks once again.

**Comment by jnskrueger** [comment]
Hi Himakar, did you get it to run?

Am Di., 12. Feb. 2019 um 00:47 Uhr schrieb Himakar Ganti <
notifications@github.com>:

**Comment by himakarganti** [comment]
Yes Jonas, it is running the SynGas mechanism I posted earlier. I sincerely appreciate your help and for working with me in resolving this.
