### ISSUE TITLE
namelist "run_pars" has an error (5010)!

### ISSUE THREAD

**Issue by yuvraj2509** [pencil-code/pencil-code#35]
While running the init_cond_3D_isotropic for isotropic turbulence I am facing this error.
I am attaching
[run.txt](https://github.com/pencil-code/pencil-code/files/4051798/run.txt)

 the run.in file Any kind of help will be appreciated

The output shown is as follows:

Found config file </home/yuvraj/Public/pencil-code/config/compilers/GNU-GCC_MPI.conf>
hostname = optiflex-790
MPI run
4 CPUs
4 nodes, 1 CPU per node
lparticles = 0
lpointmasses = 0
Subcommand: run
Revision: adc529ff1b6c22538ad6a309ba7115d450a764a6
 M src/Makefile.src
Sun Jan 12 18:52:25 2020
Running under MPI
Running 'env MODULE_PREFIX=__ MODULE_INFIX=_MOD_ MODULE_SUFFIX= /usr/bin/time -p mpiexec -n 4 ./src/run.x'...
SVN: -------            v.         (                   ) $Id$
SVN: -------            v.         (                   ) $Id$               
WARNING:  read_namelist: namelist "run_pars" has an error (5010)!

=== BEGIN SAMPLE "run.in" ===>
&run_pars
/
&eos_run_pars
/
&hydro_run_pars
/
&density_run_pars
/
&entropy_run_pars
/
&chemistry_run_pars
/
&forcing_run_pars
/
&viscosity_run_pars
/
<=== END SAMPLE ===

STOPPED: read_all_run_pars: Please fix all above WARNINGs for file "run.in"
STOP 1
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[21027,1],0]
  Exit code:    1
--------------------------------------------------------------------------
Command exited with non-zero status 1
real 0.66
user 0.51
sys 0.05
'env MODULE_PREFIX=__ MODULE_INFIX=_MOD_ MODULE_SUFFIX= /usr/bin/time -p mpiexec -n 4 ./src/run.x' failed: 
Found ERROR file from start.x
Aborting.

**Comment by WangYijun2022** [comment]
I also met the problem and con't solve it, if you had settled it, please let me know the manner, think you!

**Comment by mrheinhardt** [comment]
Hi,


I have corrected the run.in of sample

init_cond_3D_isotropic.


Best,

Matthias

________________________________
Von: WangYijun2022 ***@***.***>
Gesendet: Dienstag, 28. Februar 2023 13:41:30
An: pencil-code/pencil-code
Cc: Subscribed
Betreff: Re: [pencil-code/pencil-code] namelist "run_pars" has an error (5010)! (#35)


I also met the problem and con't solve it, if you had settled it, please let me know the manner, think you!
