### ISSUE TITLE
[JOSS] the python tutorial link is broken

### ISSUE THREAD

**Issue by zingale** [pencil-code/pencil-code#36]
The documentation here:
http://pencil-code.nordita.org/doc.php

has a link for "postprocessing with Python" but that link is broken
"Boris Dintrans wrote a comprehensive introduction to Python and postprocessing with Python."

**Comment by zingale** [comment]
https://github.com/openjournals/joss-reviews/issues/2807

**Comment by AxelBrandenburg** [comment]
The broken link was removed on Oct 9; see
https://github.com/pencil-code/website/blob/master/doc.php
but unfortunately our server stopped automatic refreshing some time ago.
The link to the wiki should be used for all python-related stuff.

**Comment by AxelBrandenburg** [comment]
The webpage has now been updated and the old broken link is removed.
