### ISSUE TITLE
[JOSS] python "is" error on import

### ISSUE THREAD

**Issue by zingale** [pencil-code/pencil-code#37]
In `derived_h5.py`, should the line 240:
```
if 'rho' is src.keys() or 'lnrho' in src.keys():
```
be
```
if 'rho' in src.keys() or 'lnrho' in src.keys()
```
?

i.e., the first `is` should be `in`?  This module complains on import (with python 3.8) about the `is`.

**Comment by zingale** [comment]
https://github.com/openjournals/joss-reviews/issues/2807

**Comment by mrheinhardt** [comment]
Has been fixed: is -> in
Thanks, zingale!

**Comment by zingale** [comment]
thanks.
