### ISSUE TITLE
[JOSS] quickstart should show sample output

### ISSUE THREAD

**Issue by zingale** [pencil-code/pencil-code#38]
Following the quickstart: http://pencil-code.nordita.org/doc/quick_start.pdf

It is hard to understand if your first run was successful.  The documentation should show an image of what the output looks like so a user can be confident it worked.

**Comment by zingale** [comment]
https://github.com/openjournals/joss-reviews/issues/2807

**Comment by mrheinhardt** [comment]
The safe way to verify the results is actually to compare with the reference data which come with each sample.
Added about this in the Quick Start Quide. Graphical output could be added to the samples, but given their often poor resolution, this is perhaps not that helpful.

**Comment by mrheinhardt** [comment]
As the webpage is not automatically updated, you would not see the updated PDF immediately, but might want to check quick_start.tex

**Comment by AxelBrandenburg** [comment]
The pdf file is on GitHub too, but in the website repository. It is now updated, but Illa may do more later today.

**Comment by AxelBrandenburg** [comment]
The life version is also now referenced in README.md.

**Comment by illarl** [comment]
Hi,

I'm just adding a couple of lines now.

**Comment by illarl** [comment]
Changes done by me.
Updated the python function names to the new version.

**Comment by zingale** [comment]
thanks for the additions.
