### ISSUE TITLE
[JOSS] contributor guidelines

### ISSUE THREAD

**Issue by zingale** [pencil-code/pencil-code#39]
The only contributor guidelines I could find are in the manual:

 > We will be happy to include user-supplied changes and updates to the code in future releases and welcome any feedback.

Contributor guidelines should also be added to the README.md, since that's probably what most people will see first, or to a CONTRIBUTING.md file (e.g., https://mozillascience.github.io/working-open-workshop/contributing/)

**Comment by zingale** [comment]
https://github.com/openjournals/joss-reviews/issues/2807

**Comment by AxelBrandenburg** [comment]
This has now been added to the README.md file.

**Comment by zingale** [comment]
awesome!  Thanks.
