### ISSUE TITLE
"init" variables in start.in are producing errors in read_namelist/sub.f90

### ISSUE THREAD

**Issue by alexrichert** [pencil-code/pencil-code#4]
Using the most recent version of the code, some (though apparently not all) parameters in start.in beginning with "init" (e.g., inituu, initaa, initxxp, initvvp) are crashing:

> WARNING:  read_namelist: namelist "particles_init_pars" has an error!
> 
> === BEGIN SAMPLE "start.in" ===>
> &init_pars
> /
> &initial_condition_pars_init_pars
> /
> &eos_init_pars
> /
> &hydro_init_pars
> /
> &density_init_pars
> /
> &special_init_pars
> /
> &particles_init_pars
> /
> &particles_nbody_init_pars
> /
> <=== END SAMPLE ===
> 
> FATAL ERROR:  read_all_init_pars: Please fix all above WARNINGs for file "start.in"

Commenting out inituu, etc. in start.in "fixes" the problem.

Also, I get a similar crash with pc_run with the following variables run.in: idiff, ivisc, iresistivity. So for samples/2d-tests/globaldisc, for example, both pc_start and pc_run crash.

**Comment by mrheinhardt** [comment]
?Hi Alex,

Which compiler do you use?

Please list all error messages you obtain of the form

?    WARNING: read_namelist: namelist "particles_init_pars" has an error!

both for start.in and run.in.

Best,

Matthias

**Comment by alexrichert** [comment]
gcc 4.9.2-6 (Fedora), with default compiler options for Linux/GNU: -O3 -fdefault-real-8 -fdefault-double-8   -std=f95

For the globaldisc example, the error for start.in is the one in the original post, and for run.in:

> WARNING:  read_namelist: namelist "viscosity_run_pars" has an error!
> 
> === BEGIN SAMPLE "run.in" ===>
> &run_pars
> /
> &eos_run_pars
> /
> &hydro_run_pars
> /
> &density_run_pars
> /
> &special_run_pars
> /
> &shock_run_pars
> /
> &viscosity_run_pars
> /
> &particles_run_pars
> /
> &particles_nbody_run_pars
> /
> <=== END SAMPLE ===
> 
> FATAL ERROR:  read_all_run_pars: Please fix all above WARNINGs for file "run.in"

which goes away if I comment out line 40 of run.in ("ivisc='nu-const','nu-shock'").

Cheers
Alex

**Comment by alexrichert** [comment]
Ah-- apparently it's the compiler! gcc 4.9.2 gives the above errors, but earlier versions seem to work.

**Comment by alexrichert** [comment]
Reopening because I'm running into the same issue with the 2013 Intel compiler suite (which used to compile Pencil no problem), so it's due to a change in the code, not the compiler per se (even though pre-4.9 gcc _is_ compiling successfully). Maybe something in the code doesn't work with a specific optimization feature, for example.
