### ISSUE TITLE
How to export the operation result?

### ISSUE THREAD

**Issue by WangYijun2022** [pencil-code/pencil-code#43]
I am a freshman in operating pencil-code, I can't find the way to export the running result after updating. If there is a instruction like ”pc_collect"? The data folder is too big for my computer to directly copy and paste. Thank you!

**Comment by zhouhz1992** [comment]
Hi Yijun,

Could you explain in more detail what do you want to do? e.g. what kind of data you wish to look at (time series/snapshots/slices/spectra etc.), or do you want to download the data you generate on a remote cluster?
Typically data files are of small sizes, except for the snapshots (VAR files).

Hongzhe

**Comment by WangYijun2022** [comment]
Thank you for incoming letter! I want to output the temperature curve at different times and the concentration curve of each reactant, and calculate the heat release rate of the intermediate reaction process.


---Original---
From: "Hongzhe ***@***.***&gt;
Date: Sun, Nov 6, 2022 21:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pencil-code/pencil-code] How to export the operation result?(Issue #43)




 
Hi Yijun,
 
Could you explain in more detail what do you want to do? e.g. what kind of data you wish to look at (time series/snapshots/slices/spectra etc.), or do you want to download the data you generate on a remote cluster?
 Typically data files are of small sizes, except for the snapshots (VAR files).
 
Hongzhe

**Comment by zhouhz1992** [comment]
Unfortunately I'm not quite familiar with these outputs. Maybe other people are. You can also post your questions on https://groups.google.com/g/pencil-code-discuss and more people are available there I think.

**Comment by mrheinhardt** [comment]
Hi Yijun,


the chemistry module has a number of specific diagnostics:

volume averages and extrema for each species: Ym through diffm (check in chemistry.f90 for variables idiag_*), put in print.in.

xy-averages: Ymz (averaged concentration, put in xyaver.in


You can get the concentrations also in slices by putting chemspec<i>

(i for the species) in video.in.


I can't see a diagnostic containing the heat release rate (RHS_T_full) yet. You had to consider coding it yourself then following the pattern of other diagnostics.


You can get the xy-averaged temperature as a function of z and time by TTmz in xyaver.in


Best,

Matthias

________________________________
Von: Hongzhe Zhou ***@***.***>
Gesendet: Montag, 7. November 2022 05:00:07
An: pencil-code/pencil-code
Cc: Subscribed
Betreff: Re: [pencil-code/pencil-code] How to export the operation result? (Issue #43)


Unfortunately I'm not quite familiar with these outputs. Maybe other people are. You can also post your questions on https://groups.google.com/g/pencil-code-discuss and more people are available there I think.
