### ISSUE TITLE
Hebbe, mpif90 error

### ISSUE THREAD

**Issue by xiang-yu** [pencil-code/pencil-code#6]
Dear all, 

The code can compile sucessfully on **Hebbe**, but could not
run because of the **mpi error**.

Setup in the "Makefile.src" file is,  
# FC=ifort #(hebbe)
# FFLAGS= -O2 #(hebbe)
# FC=mpif90 #(hebbe)
# CC=mpicc #(hebbe)
# CFLAGS=-O3 -DFUNDERSC=1 #(hebbe)
# LD_MPI= #(hebbe)
# FFLAGS_DOUBLE=-fdefault-real-8 #(hebbe)
# LIBMPISUFFIX=#(hebbe)

*_Error report: *_
4 CPUs
HOSTNAME = hebbe08-3
USER = lixian
Running under MPI
masterhost=hebbe
Simple Linux Utility for Resource Management (SLURM) job
SLURM_NODELIST = hebbe08-3
nodelist = hebbe08-3
SLURM_TASKS_PER_NODE = 20
Generic setup; hostname is <hebbe08-3>.
No valid 'mpirun' setting, use default 'mpiexec'.
datadir = data
Setting nodelist to node hebbe08-3
$mpi            =  <2>
$ncpus          =  <4>
$npops          =  <-n 4>
$local_disc     =  <0>
$one_local_disc =  <1>
$remote_top     =  <0>
$local_binary   =  <0>
$datadir        =  <data>
$SCRATCH_DIR    =  </scratch/pencil-8202>
$hn             =  <hebbe08-3>
$masterhost     =  <hebbe>
$mpirun         =  <mpiexec>
$mpirunops      =  <>
$mpirunops2     =  <>
$x_ops          =  <>
$NODELIST       =  <hebbe08-3>
$SSH            =  <ssh>
$SCP            =  <scp>
$PARENT_PID     =  <8202>
$copysnapshots  =  <copy-snapshots>
$particles      =  <1>
$particles_nbody=  <0>
tor mar 31 10:51:20 CEST 2016
mpiexec  -n 4  src/start.x
  File "/c3se/apps/Common/intel/ips_xe_ce_2016/impi/5.1.1.109/bin64/mpiexec", line 187
    except EOFError, e:
                   ^
SyntaxError: invalid syntax
0.030u 0.061s 0:00.98 9.1%      0+0k 0+0io 427pf+0w

tor mar 31 10:51:21 CEST 2016
Error status 1 found -- aborting

Here is the sample used as a test, 
/pencil-code/samples/dust_turb_globaldisk/

Does anyone come across the same problem?

Best,

Xiangyu

**Comment by belfhi** [comment]
Hello,
are you sure 'mpif90' is the intel compiler wrapper for ifort? On many
systems it's mpiifort & mpiicc,
maybe you are mixing the gcc wrappers with Intel MPI mpiexec?
Cheerrs,
Johannes

2016-03-31 11:07 GMT+02:00 Xiangyu LI notifications@github.com:

**Comment by xiang-yu** [comment]
Hi,
Thanks. 
I tried the following, 
#FC=ifort #(hebbe)
#FFLAGS= -O2 #(hebbe)
#FC=mpiifort  #(hebbe)
#CC=mpiicc #(hebbe)
#CFLAGS=-O3 -DFUNDERSC=1 #(hebbe)
#LD_MPI= #(hebbe)
#FFLAGS_DOUBLE=-r8 #(hebbe)
#LIBMPISUFFIX=#(hebbe)

It reported the same error.

**Comment by belfhi** [comment]
Seems like you're having a python problem,
mpiexec is a python script for Intel MPI
Try using the mpirun command,:q
 which is a shell script.
Maybe that will work.
-johannes

2016-03-31 11:46 GMT+02:00 Xiangyu LI notifications@github.com:

**Comment by xiang-yu** [comment]
I do not quite understand. 
You mean add ":q" in the "start.csh"  or "run.csh"?

**Comment by belfhi** [comment]
Oh sorry that ':q' doesn't belong there. Just use mpirun instead of mpiexec.
Am 31.03.2016 12:40 nachm. schrieb "Xiangyu LI" notifications@github.com:

I do not quite understand.
You mean add ":q" in the "start.csh" or "run.csh"?
