### ISSUE TITLE
Paraller run not working

### ISSUE THREAD

**Issue by kedarbhide** [pencil-code/pencil-code#8]
I'm running _samples/turbulence/helical-MHDturb32-4procs_ .It runs succesfully with one processor.
With multiple procssors, after pc_build command I get error with **mpif.h** file. I copied this file from MPI install directory to local src and tried pc_build and then I get error saying _undefined reference to mpi_send..._
FAQs in maual suggest to add _ (Underscore) in Makefile.local but that also doesn't work. Same error appears again. Errors at end say **waiting for unfinished jobs** .
Can anybody help?

**Comment by belfhi** [comment]
Build with mpif90 instead of gfortran (or mpiifort instead of ifort if
you're using the Intel compilers)
Am 02.06.2016 3:25 nachm. schrieb "kedarbhide" notifications@github.com:

**Comment by PABourdin** [comment]
If you use pc_build and want to have MPI compilers, you need to select the matching compiler configuration that you can recognize by its ending "_MPI", like "pc_build -f GNU-GCC_MPI".
